pragma circom 2.2.3;

include "circomlib/circuits/comparators.circom";
include "circomlib/circuits/poseidon.circom";

// Proves (value OP threshold) without revealing value.
// Outputs a Poseidon commitment binding value to the proof.
//
// Private inputs:  value_scaled  (element % * 10, e.g. 32.5 → 325)
//                  salt          (random field element, generated by prover)
// Public inputs:   threshold_scaled, is_gt
// Public outputs:  result, commitment
template ElementThreshold() {
    signal input value_scaled;
    signal input salt;
    signal input threshold_scaled;
    signal input is_gt;

    signal output result;
    signal output commitment;

    // commitment = Poseidon(value_scaled, salt)
    component h = Poseidon(2);
    h.inputs[0] <== value_scaled;
    h.inputs[1] <== salt;
    commitment <== h.out;

    // threshold comparison
    component gt = GreaterThan(10);
    gt.in[0] <== value_scaled;
    gt.in[1] <== threshold_scaled;

    component lt = LessThan(10);
    lt.in[0] <== value_scaled;
    lt.in[1] <== threshold_scaled;

    signal gt_branch <== is_gt * gt.out;
    signal lt_branch <== (1 - is_gt) * lt.out;
    result <== gt_branch + lt_branch;
}

component main {public [threshold_scaled, is_gt]} = ElementThreshold();
